### ISSUE TITLE
Built-in message box button text clips

### ISSUE THREAD

**Issue by GF-Huang** [canton7/Stylet#254] opened 2021-05-08 09:48 UTC
**Description**
![image](https://user-images.githubusercontent.com/4510984/117534783-7baac600-b025-11eb-9248-41f911b89d8d.png)

**To Reproduce**
`Container.Get<IWindowManager>().ShowMessageBox("测试", "标题");`

**Version Info**
 - Stylet version: 1.3.6
 - Runtime version: .net 5
 
**Additional Info**

**Comment by canton7** [comment] 2021-05-09 09:20
Duplicate of #138?

Please don't open both an issue and a discussion. Follow the instructions and open a discussion, and leave it at that.

**Closed by canton7** 2021-05-09 09:20 UTC
