### ISSUE TITLE
net core WPF “TouchEnter”  evnet have trublle

### ISSUE THREAD

**Issue by Zellear** [canton7/Stylet#166] opened 2020-11-09 08:08 UTC
![image](https://user-images.githubusercontent.com/52039441/98514807-04c68780-22a5-11eb-9d69-ac43f7be6152.png)
![image](https://user-images.githubusercontent.com/52039441/98514948-40f9e800-22a5-11eb-9aee-562aaa8952bf.png)
![image](https://user-images.githubusercontent.com/52039441/98514839-11e37680-22a5-11eb-9a60-1df9ef2d16d5.png)
Please ask how to solve it.

**Comment by canton7** [comment] 2020-11-09 08:10
Duplicate of #97. A quirk of WPF means you can't use actions with TouchEnter, sorry. Use an event in the code behind.

**Closed by canton7** 2020-11-09 08:10 UTC
